import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./header";
import { ThemeProvider } from "@/components/theme-provider"

import { Button } from "@/components/ui/button";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet";
import { cookies } from "next/headers";
import { verifyJWT, decodeJWT } from "@/lib/middleware/functions";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;
  let user = null;
  if (token) {
    const isValid = verifyJWT(token);
    console.log("Token validity:", isValid);
    if (isValid) {
      user = decodeJWT(token);
      console.log("User info:", user);
      
    }
    else {
      console.log("Invalid token");
    }
  } else {
    // Handle missing token scenario
    console.log("No token found");
  }
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex min-h-screen flex-col">
            <Sheet>
              <Header user={user}/>
              <Sidebar />
            </Sheet>
            <div className="flex flex-1">
              <main className="flex-1 p-6">{children}</main>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

const Sidebar = () => (
  
    
    <SheetContent side="left">
      <SheetHeader>
        <SheetTitle>Navigation</SheetTitle>
      </SheetHeader>
      <nav className="flex flex-col gap-4 p-4">
        <div className="flex flex-col gap-2">
          <h3 className="font-semibold text-sm">Dashboard</h3>
          <a
            className="pl-4 text-muted-foreground text-sm hover:text-foreground"
            href="#"
          >
            Overview
          </a>
          <a
            className="pl-4 text-muted-foreground text-sm hover:text-foreground"
            href="#"
          >
            Analytics
          </a>
        </div>
        <div className="flex flex-col gap-2">
          <h3 className="font-semibold text-sm">Settings</h3>
          <a
            className="pl-4 text-muted-foreground text-sm hover:text-foreground"
            href="#"
          >
            Profile
          </a>
          <a
            className="pl-4 text-muted-foreground text-sm hover:text-foreground"
            href="#"
          >
            Account
          </a>
        </div>
      </nav>
    </SheetContent>
  
);
